"""Storage-agnostic interfaces. `backend/storage.py` depends only on these Protocols, never
on a concrete database — swapping the backing implementation (Postgres today, something
else later) means writing a new class that satisfies these shapes, nothing more."""

from typing import List, Protocol

from .models import Project, ProjectSummary, Template, TemplateNode, TemplateSummary


class ProjectRepository(Protocol):
    def list_summaries(self) -> List[ProjectSummary]: ...

    def load(self, project_id: str) -> Project: ...

    def save(self, project: Project) -> None: ...

    def create(self, name: str) -> Project: ...

    def delete(self, project_id: str) -> None: ...

    def rename(self, project_id: str, name: str) -> Project: ...


class TemplateRepository(Protocol):
    def list_summaries(self) -> List[TemplateSummary]: ...

    def load(self, template_id: str) -> Template: ...

    def save_new(self, name: str, root: TemplateNode) -> Template: ...

    def delete(self, template_id: str) -> None: ...
